runtime: python37
handlers:
  - url: /(.*\.(gif|png|jpeg|jpg|css|js|ico|map|woff|woff2|ttf))$
    static_files: dist/\1
    upload: dist/(.*)
    secure: always
    redirect_http_response_code: 301
  - url: /(.*)
    static_files: dist/index.html
    upload: dist/index.html
    secure: always
    redirect_http_response_code: 301
