runtime: python39
handlers:
  - url: /(.*\.(gif|png|jpeg|jpg|css|js|ico|map|woff|woff2|ttf))$
    static_files: dist/plohl-com/browser/\1
    upload: dist/plohl-com/browser/(.*)
    secure: always
    redirect_http_response_code: 301
  - url: /(.*)
    static_files: dist/plohl-com/browser/index.html
    upload: dist/plohl-com/browser/index.html
    secure: always
    redirect_http_response_code: 301
